# Generated by Django 5.1.2 on 2025-01-03 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='updated_at',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
    ]
