# Generated by Django 5.1.2 on 2025-01-04 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_customermodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='adressmodel',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
